In [5]:
import numpy as np
#1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

a = np.array([1, 2, 3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
#2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
b=np.array([[0,0,0], [0,0,0], [0,0,0]])

b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
#3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та 
# виведіть його значення.
    
c = np.random.randint(1, 10, size=(5, 5))
c

array([[7, 1, 2, 3, 6],
       [8, 7, 2, 7, 8],
       [2, 3, 5, 4, 5],
       [8, 7, 5, 8, 3],
       [5, 3, 5, 3, 9]], dtype=int32)

In [13]:
#4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та 
#виведіть його значення.

d = np.random.random(size=(4, 4))
d

array([[0.98347532, 0.53575308, 0.46979087, 0.05312449],
       [0.37685871, 0.69213944, 0.08712064, 0.94187642],
       [0.55408937, 0.35415874, 0.0622727 , 0.18935165],
       [0.7191117 , 0.30528801, 0.27998782, 0.33747328]])

In [18]:
#5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, 
#віднімання та множення.
e=np.random.randint(1,10, size=(1,5))
f=np.random.randint(1,10, size=(1,5))

In [48]:
print(e, f)


[[2 8 8 5 1]] [[1 2 1 4 6]]


In [20]:
print(e+f)
print(e-f)
print(e*f)

[[ 3 10  9  9  7]]
[[ 1  6  7  1 -5]]
[[ 2 16  8 20  6]]


In [28]:
#6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

g=np.random.uniform(1,100, size=7)
h=np.random.uniform(1,100, size=7)
print(np.dot(g,h))

11407.604428233366


In [32]:
#7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 
#та перемножте їх між собою.
m1=np.random.randint(1, 10, size=(2, 3))
m2=np.random.randint(1, 10, size=(2, 3))
print(m1*m2)

[[ 6 18 16]
 [20 42 54]]


In [40]:
#8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні 
#від 1 до 10 та знайдіть її обернену матрицю.

m3=np.random.randint(1, 10, size=(3, 3))
m3_inv=np.linalg.inv(m3)
m3_inv

array([[-0.265625,  0.734375, -0.34375 ],
       [ 0.25    , -0.75    ,  0.5     ],
       [ 0.375   , -0.625   ,  0.25    ]])

In [42]:
#9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1
# та транспонуйте її.
m4=np.random.uniform(0, 1, size=(4, 4))
print(m4.T)

[[0.28409484 0.4555903  0.52438417 0.50670669]
 [0.50012132 0.38783077 0.2657136  0.13738495]
 [0.23809004 0.72234576 0.27976113 0.22834131]
 [0.99598578 0.28621469 0.27571374 0.44611094]]


In [50]:
#10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні 
#від 1 до 10 та перемножте матрицю на вектор.
m6=np.random.randint(1, 10, size=(3, 4))
v6=np.random.randint(1, 10, size=4)
print(m6*v6)

[[56  3 20  6]
 [42  9 20  1]
 [63  5 15  4]]


In [13]:
#11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 
# та перемножте матрицю на вектор.
m4=np.random.uniform(0, 1, size=(2, 3))
v4=np.random.uniform(0, 1, size=3)
print(m4*v4)

[[0.18899531 0.16837697 0.11999805]
 [0.29204048 0.14267605 0.29751101]]


In [47]:
#12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні 
#від 1 до 10 та виконайте їхнє поелементне множення.
m5=np.random.randint(1, 10, size=(2, 2))
m6=np.random.randint(1, 10, size=(2, 2))
print(m5* m6)

[[21 63]
 [ 6 16]]


In [7]:
#13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні 
#від 1 до 10 та знайдіть їх добуток.

m5=np.random.randint(1, 10, size=(2, 2))
m6=np.random.randint(1, 10, size=(2, 2))
print(m5* m6)

[[ 6  2]
 [18  7]]


In [10]:
#14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні 
# від 1 до 100 та знайдіть суму елементів матриці.
m14=np.random.randint(1, 100, size=(5, 5))
ls=[]
for i in range(0, 5):
    for j in range(0, 5):
        ls.append(m14[i, j])
s=sum(ls)
print(s)

1324


In [14]:
#15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні
# від 1 до 10 та знайдіть їхню різницю.

m15=np.random.randint(1, 10, size=(4, 4))
m_16=np.random.randint(1, 10, size=(4, 4))
print(m15-m_16)

[[ 2  2  0 -6]
 [ 4 -5  0  2]
 [-3  5 -3 -6]
 [-8  4  1  1]]


In [17]:
#16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та 
#знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

m16=np.random.uniform(0, 1, size=(3, 3))
for i in range(0, 3):
    v16=m16[i]
    v16_sum=sum(v16)
    print(v16_sum)

1.7346828990537606
1.9595254980536514
1.617911261050771


In [24]:
#17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
m17=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m17_q = np.ones((3, 4), dtype=int)
for i in range(0, 3):
    for j in range(0, 4):
        m17_q[i, j]=m17[i, j]**2
        
print(m17_q)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [29]:
#18Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 
#та знайдіть вектор з квадратними коренями цих чисел.
v18=np.random.randint(1, 50, size=4)
v18_q=v18**0.5
print(v18_q)

[2.82842712 2.23606798 1.73205081 6.92820323]
