In [4]:
import numpy as np
#1. Замініть усі непарні числа в arr на -1 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for i in range(0,9):
    if arr[i]%2==1:
        arr[i]=-1
arr   

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8,  9])

In [8]:
#2. Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками
arr_1d = np.arange(10) 
arr_2d = arr_1d.reshape(2, -1)
print(arr_1d, "\n", arr_2d,)

[0 1 2 3 4 5 6 7 8 9] 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
#3. Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

res = np.vstack((a, b))
print(res)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
#4. Створіть наступний шаблон без жорсткого кодування(Hard coding) . 
#Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3])
#Input:
a4 = np.array([1,2,3])
#Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
part1 = np.repeat(a4, 3)
part2 = np.tile(a4, 3)

result = np.concatenate((part1, part2))

print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [21]:
#5. Отримайте спільні елементи між a і b

a5 = np.array([1,2,3,2,3,4,3,4,5,6]) 
b5 = np.array([7,2,10,2,7,4,9,4,9,8])

common = np.intersect1d(a5, b5)

print(common)

[2 4]


In [22]:
#6. Отримайте позиції перших 5 максимальних значень у заданому масиві a

np.random.seed(100) 
a6 = np.random.uniform(1,50, 20)
top_5_indices = np.argsort(a6)[-5:][::-1]

print(a6[top_5_indices])

[48.95256545 44.67477576 42.39403048 41.466785   40.99501269]


In [24]:
#7. Вилучіть усі значення NaN із одновимірного масиву

a7 = np.array([1,2,3,np.nan,5,6,7,np.nan])  

clean_a = a7[~np.isnan(a7)]

print(clean_a)

[1. 2. 3. 5. 6. 7.]


In [25]:
#8. Обчисліть евклідову відстань між двома масивами a і b.
a8 = np.array([1,2,3,4,5]) 
b8 = np.array([4,5,6,7,8])
distance = np.sqrt(np.sum((a8 - b8) ** 2))
print(distance)

6.708203932499369


In [27]:
#9. Знайдіть індекс 5-го повторення числа 1 у масиві x

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

indices = np.where(x == 1)[0]

fifth_index = indices[4]

print( fifth_index)

8


In [29]:
#10. Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. 
#Перше повторення має бути False.

# Input np.random.seed(100) a = np.random.randint(0, 5, 10)
#[0 0 3 0 2 4 2 2 2 2] #Output [False True False True False False True True True True]

np.random.seed(100)
a = np.random.randint(0, 5, 10)
seen = {}
result = []

for val in a:
    if val in seen:
        result.append(True)
    else:
        result.append(False)
        seen[val] = True

result = np.array(result)
print(result)

[False  True False  True False False  True  True  True  True]
